# Generated by Django 5.0.3 on 2024-03-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_user_agreed_to_terms'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='contact_table',
        ),
    ]
